### PR TITLE
Fix socket auth

### LINKED ISSUE #455: 1.0 authentication service hooks don't run when client uses feathers-socketio
The authentication service hooks don't get hit when I use the `feathers-socketio` transport.  In the example, below, the hook only runs if I use `feathers-rest`.

```js
app.service('authentication').hooks({
  before: {
    create: [function (hook) {
      // OOPS, this only runs during requests from feathers-rest
      console.log(hook);
    }]
  },
  after: {
    create: [authHook(options)]
  }
});
```

### PR DESCRIPTION
**Pull request by marshallswain**
Closes #455, #448, and #432

I left a couple of `debugger`s in that aren't getting it in the rest.test.js file when testing events  (search for `it.only`).

This change channels socket auth through the token service instead of calling app.authenticate manually before hitting the token service.

This also makes it so the client has to provide a strategy explicitly, and removes the strategy iteration from `passport/authenticate.js`.

Also updates tests.

### CODE REVIEW

File: src/socket/handler.js [hunk 1]
```diff
@@ -57,135 +55,94 @@ export default function setupSocketHandler (app, options, { feathersParams, prov
...
       const { strategy } = data;
-      const body = omit(data, 'strategy');
-
+      // const body = omit(data, 'strategy');
       socket._feathers = {
         query: {},
-        params: {},
-        body,
+        provider: 'socketio',
+        // body: data,
```
Comment (marshallswain) [inline src/socket/handler.js]: Needs to be removed?

File: test/integration/rest.test.js [hunk 2]
```diff
@@ -441,7 +441,7 @@ describe('REST authentication', function () {
     });
 
     describe('when authentication succeeds', () => {
-      it('emits login event', done => {
+      it.only('emits login event', done => {
```
Comment (marshallswain) [inline test/integration/rest.test.js]: This is the failing test.  Well, one of two that are failing for what looks like the same cause.

File: src/express/authenticate.js [hunk 3]
```diff
@@ -11,6 +11,7 @@ export default function authenticate (strategy, options = {}) {
 
   return function (req, res, next) {
     // If we are already authenticated skip
+    debugger;
```
Comment (marshallswain) [inline src/express/authenticate.js]: This `debugger` never gets hit.

File: src/hooks/authenticate.js [hunk 4]
```diff
@@ -19,13 +20,29 @@ export default function authenticate (strategy, options = {}) {
...
+        strategy = strategies;
+      }
+    }
+
+    // Handle the case where authenticate hook was registered without a passport strategy specified
+    if (!strategy) {
+      return Promise.reject(new errors.GeneralError(`You must provide an authentication 'strategy'`));
+    }
+
     // NOTE (EK): Bring this in when we decide to make the strategy required by the client
```
Comment (ekryski) [inline src/hooks/authenticate.js]: We can remove this note. `strategy` is required now.

File: src/passport/authenticate.js [hunk 5]
```diff
@@ -21,10 +21,21 @@ export default function authenticate (options = {}) {
         // Allow you to set a location for the success payload.
         // Default is hook.params.user, req.user and socket.user.
         const entity = strategyOptions.entity || strategyOptions.assignProperty || options.entity;
-        let failures = [];
-        let strategies;
+        let strategyName = request.body && request.body.strategy;
```
Comment (ekryski) [inline src/passport/authenticate.js]: This should probably be:

```js
request.body = request.body || {};
let stategyName = request.body.strategy;
```

File: src/socket/handler.js [hunk 6]
```diff
@@ -57,135 +55,92 @@ export default function setupSocketHandler (app, options, { feathersParams, prov
...
-      if (!strategy) {
-        const error = new errors.BadRequest(`An authentication 'strategy' must be provided.`);
-        return callback(normalizeError(error));
-      }
-
-      if (!app.passport._strategy(strategy)) {
-        const error = new Error(`Your '${strategy}' authentication strategy is not registered with passport.`);
-        return callback(normalizeError(error));
-      }
+      // if (!strategy) {
```
Comment (ekryski) [inline src/socket/handler.js]: This can be removed.

File: src/socket/handler.js [hunk 7]
```diff
@@ -57,135 +55,92 @@ export default function setupSocketHandler (app, options, { feathersParams, prov
...
-            //   return {
-            //     redirect: true,
-            //     status: 302,
-            //     url: stategyOptions.successRedirect
-            //   };
-            // }
-            return Promise.resolve(result.data);
-          }
+      // if (!app.passport._strategy(strategy)) {
+      //   const error = new Error(`Your '${strategy}' authentication strategy is not registered with passport.`);
```
Comment (ekryski) [inline src/socket/handler.js]: This can also be removed

File: src/socket/handler.js [hunk 8]
```diff
@@ -57,135 +55,92 @@ export default function setupSocketHandler (app, options, { feathersParams, prov
...
-          // }
-
-          // NOTE (EK): This handles redirects and .pass()
-          return Promise.reject(new errors.NotAuthenticated('Authentication could not complete. You might be using an unsupported socket authentication strategy. Refer to docs.feathersjs.com for more details.'));
-        })
-        .then(result => {
-          // Now that we are authenticated create our JWT access token
-          const params = Object.assign({ authenticated: true }, result);
-          return service.create(result, params).then(tokens => {
+      // const promise = app.authenticate(strategy, strategyOptions)(socket._feathers)
```
Comment (ekryski) [inline src/socket/handler.js]: This can be removed
